-- ENUM-ONLY MIGRATION (commit alone first)
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'CONFIRMED';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'QUEUED';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
